### ISSUE TITLE
K1 errors when started looking for vcruntime.

### ISSUE THREAD

**Issue by vegaslon** [kasenvr/hifi-community#4]
K1 errors when started looking for vcruntime.

**Comment by kasenvr** [comment]
Looking into that one.

**Comment by kasenvr** [comment]
Please try this build of K2: https://realities.dev/cdn/hifi-community/v0860-kasen-VS-release+freshstart-k2/Packaged_Release.zip

**Comment by kasenvr** [comment]
We've found that this issue happens because the proper distributables are not shipped with the app due to not having an installer. We are looking into perhaps putting the required .dlls in the source folder and/or until we can get an installer going. We're experimenting with the various options.
